AWSTemplateFormatVersion: 2010-09-09
Description: Billing Alerts for AWS Account
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'Billing Parameters'
      Parameters:
      - TriggerOne
      - TriggerTwo
      - TriggerThree
      - TriggerFour
      - TriggerFive

Parameters:
  Email:
    Type: String
    Default: your@email.com
    Description: Your email address to receive alarms per email
  TriggerOne:
    Description: 'One trigge $ alerts.'
    Type: String
    Default: '20'
  TriggerTwo:
    Description:  'Tow trigge $ alerts.'
    Type: String
    Default: '50'
  TriggerThree:
    Description:  'Three trigge $ alerts.'
    Type: String
    Default: '100'
  TriggerFour:
    Description:  'Four trigge $ alerts.'
    Type: String
    Default: '500'
  TriggerFive:
    Description:  'Five trigge $ alerts.'
    Type: String
    Default: '1000'
Resources:
  BillingAlertOne:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref BillingAlertTopic
      AlarmDescription: !Join ["", [Billing Alert for $, !Ref TriggerOne]]
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Currency
          Value: USD
      EvaluationPeriods: 1
      MetricName: EstimatedCharges
      Namespace: AWS/Billing
      Period: 86400
      TreatMissingData: breaching
      Statistic: Maximum
      Threshold: !Ref TriggerOne

  BillingAlertTwo:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref BillingAlertTopic
      AlarmDescription: !Join ["", [Billing Alert for $, !Ref TriggerTwo]]
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Currency
          Value: USD
      EvaluationPeriods: 1
      MetricName: EstimatedCharges
      Namespace: AWS/Billing
      TreatMissingData: breaching
      Period: 86400
      Statistic: Maximum
      Threshold: !Ref TriggerTwo

  BillingAlertThree:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref BillingAlertTopic
      AlarmDescription: !Join ["", [Billing Alert for $,  !Ref TriggerThree]]
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Currency
          Value: USD
      EvaluationPeriods: 1
      MetricName: EstimatedCharges
      Namespace: AWS/Billing
      TreatMissingData: breaching
      Period: 86400
      Statistic: Maximum
      Threshold:  !Ref TriggerThree

  BillingAlertFour:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref BillingAlertTopic
      AlarmDescription: !Join ["", [Billing Alert for $,  !Ref TriggerFour]]
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Currency
          Value: USD
      EvaluationPeriods: 1
      MetricName: EstimatedCharges
      Namespace: AWS/Billing
      TreatMissingData: breaching
      Period: 86400
      Statistic: Maximum
      Threshold:  !Ref TriggerFour

  BillingAlertFive:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref BillingAlertTopic
      AlarmDescription: !Join ["", [Billing Alert for $,  !Ref TriggerFive]]
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Currency
          Value: USD
      EvaluationPeriods: 1
      MetricName: EstimatedCharges
      Namespace: AWS/Billing
      TreatMissingData: breaching
      Period: 86400
      Statistic: Maximum
      Threshold:  !Ref TriggerFive

  BillingAlertTopic:
    Type: AWS::SNS::Topic

  AlarmSubscriberEmail:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref Email
      Protocol: email
      TopicArn: !Ref BillingAlertTopic
